print('''Ingrese los siguientes datos para realizar su compra
      Todos los datos son obligatorios''')
nombre=input("Ingrese su nombre: ")
telefono=input("Ingrese su telefono: ")
print("Ingrese producto y cantidad")
producto=input("Nombre del producto: ")
cant=input("Cantidad:  ")
op=input("¿Seguro que desea pagar? (si o no)")
if nombre=="" or telefono=="" or producto=="" or cant=="":
    print("Faltan datos por ingresar")
    print(f"Nombre: {nombre}")
    print(f"Telefono: {telefono}")
    print(f"Producto: {producto}")
    print(f"Cantidad: {cant}")
    nombre=input("Ingrese su nombre: ")
    telefono=input("Ingrese su telefono: ")
    print("Ingrese producto y cantidad")
    producto=input("Nombre del producto: ")
    cant=input("Cantidad:  ")
    op=input("¿Seguro que desea pagar? (si o no): ")
